---

- include_vars: install.yml
  tags:
    - homebrew

- name: register homebrew install path
  stat: "path={{ homebrew.install.path }}"
  register: homebrew_install_path
  ignore_errors: False

- fail: msg="Homebrew install path ({{ homebrew.install.path }}) does not exist!"
  when: homebrew_install_path.stat.exists == False

- name: ensure homebrew bin permissions are set
  file:
    path: "{{ homebrew.install.path }}/bin"
    group: admin
    mode: 0775
    state: directory
    recurse: true
  tags:
    - homebrew

- name: register homebrew binary
  stat: "path={{ homebrew.install.path }}/bin/brew"
  register: homebrew_binary
  tags:
    - homebrew

- name: ensure homebrew is installed
  git:
    repo: "{{ homebrew.git.repository }}"
    version: "{{ homebrew.git.branch }}"
    dest: "{{ homebrew.install.path }}"
    update: no
    accept_hostkey: yes
  when: homebrew_binary.stat.exists == False
  tags:
    - homebrew
