---

- include_vars: packages.yml

- name: register apm binary
  stat: "path=apm"
  register: apm_binary

- name: register package states
  stat: "path=~/.atom/packages/{{ item }}"
  register: "atom_package_stat"
  with_items: atom.packages

- name: install Atom packages
  command: "apm install {{ item.item }}"
  when: item.stat.exists == False
  with_items: atom_package_stat.results
