---

- include_vars: environment.yml
  tags:
    - development

- name: ensure development base directory is created
  file:
    path: "{{ development.environment.base_dir }}"
    state: directory
    mode: 0755
  tags:
    - development
