---

- include_vars: env.yml
  tags:
    - development

- include_vars: github.yml
  tags:
    - development

- name: ensure github repositories are cloned
  git:
    repo: "git://github.com/{{ item.repo }}.git"
    dest: "{{ env.base_dir }}/{{ item.dest | default (item.repo) }}"
    clone: "{{ item.clone | default ('yes') }}"
    update: "{{ item.latest | default ('no') }}"
  with_items: "{{ github.repositories }}"
  tags:
    - development
