---

- include_vars: safari.yml
  tags:
    - common

- name: ensure osx defaults are configured
  command: "defaults write {{ common.settings.safari.class }} {{ item.key }} -{{ item.value.type }} {{ item.value.value }}"
  with_dict: "{{ common.settings.safari.properties }}"
  tags:
    - common
