---

- name: register xcode-cli tools state
  command: "xcode-select -p"
  register: xcode_cli_state
  ignore_errors: True

- name: ensure Apple command line tools are installed
  command: "xcode-select --install"
  when: xcode_cli_state|failed
