---

- include_vars: config.yml

- name: ensure vim base directory exists
  file:
    path: "{{ vim.config.path }}"
    owner: "{{ ansible_user_id }}"
    group: "staff"
    mode: 0755
    state: directory

- name: "ensure vim.d directories exist"
  file:
    path: "{{ vim.config.path }}/{{ item }}"
    owner: "{{ ansible_user_id }}"
    group: "staff"
    mode: 0755
    state: directory
  with_items:
    - backups
    - colors
    - swaps
    - syntax
    - undo
